name: Sync MLX Files

on:
  push:
    branches: [ master ]
    paths:
    - '**.mlx'

jobs:
  copy-changes:
    runs-on: self-hosted
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v2
        with:
          repository: 'pavan-kumar-s/COBRA.tutorials'
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Get All Changed Files
        id: files
        uses: jitterbit/get-changed-files@v1

      - name: Find changed files
        id: getfile
        run: |
            files=$(echo "${{ steps.files.outputs.all }}" | tr ' ' '\n' | grep -E '\.mlx$')
            echo "::set-output name=file::$files"
      
      
      - name: Give execute permission to the script
        run: chmod +x build.sh
        
      - name: Give execute permission to the other script  
        run: chmod +x setup.sh

           
      - name: Sync with Destination Repo
        run: |
          for file in ${{ steps.getfile.outputs.file }}; do
              ./build.sh pavan-kumar-s/cobratoolbox $file
