name: Sync MLX Files

on:
  push:
    branches: [ master ]
    paths:
    - '**.mlx'

jobs:
  copy-changes:
    runs-on: self-hosted
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v2
        with:
          repository: 'pavan-kumar-s/COBRA.tutorials'
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          
      - name: Get All Changed Files
        id: files
        uses: jitterbit/get-changed-files@v1
        
      - name: Clone the destination repository
        run: |
          rm -rf cobratoolbox
          echo "Cloning the destination repository: git@github.com:pavan-kumar-s/cobratoolbox.git"
          git clone --depth 1 git@github.com:pavan-kumar-s/cobratoolbox.git
          
      - name: Sinc with destination repository
        run: |
          # Setup virtual frame buffer
          export DISPLAY=:100
          echo "Starting virtual frame buffer..."
          Xvfb -ac :100 -screen 0 1280x1024x24 > /dev/null &
          for file in $(echo "${{ steps.files.outputs.all }}" | tr ' ' '\n' | grep '\.mlx$'); do
            if [[ "${{ steps.files.outputs.all }}" != "" ]]; then
              echo "Processing: $file"
              ./build.sh pavan-kumar-s/cobratoolbox $file
            fi
          done
        
      - name: Pushing the changes to both COBRA.tutorials and cobratoolbox repos
        run: |
          # Set up git config
          echo "Setting up git config..."
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # Add, commit, and push the changes
          cd cobratoolbox
          git add .
          git commit -m "Sync files from source repo" || echo "No changes to commit"
          git push origin master
          cd ..
          rm -rf cobratoolbox
          git add .
          git commit -m "created .HTML, .pdf and .m files"
          git push origin master
          echo "Script execution completed."
